# Generated by Django 3.2.7 on 2021-09-29 18:04

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='добавлен в'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='wished_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='wished_items', to=settings.AUTH_USER_MODEL, verbose_name='нужен'),
        ),
    ]
