# Generated by Django 3.2.7 on 2021-10-04 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='контакты'),
        ),
    ]
