# Generated by Django 3.2.7 on 2021-09-30 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barter', '0002_auto_20210929_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='wished_by',
            field=models.ManyToManyField(blank=True, related_name='wished_items', to=settings.AUTH_USER_MODEL, verbose_name='нужен'),
        ),
    ]
