# Generated by Django 3.2.7 on 2021-10-02 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# barter.migrations.0005_auto_20211002_1633


def create_through_relations(apps, schema_editor):
    Item = apps.get_model('barter', 'Item')
    Wish = apps.get_model('barter', 'Wish')
    for item in Item.objects.all():
        for wisher in item.wished_by.all():
            Wish(
                item=item,
                wisher=wisher,
                wished_at=datetime.datetime.now(),
            ).save()


class Migration(migrations.Migration):

    replaces = [('barter', '0004_wish'), ('barter', '0005_auto_20211002_1633'), ('barter', '0006_remove_item_wished_by'), ('barter', '0007_item_wished_by')]

    dependencies = [
        ('barter', '0003_alter_item_wished_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wished_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='пожелали в')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='barter.item', verbose_name='предмет')),
                ('wisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wisher', to=settings.AUTH_USER_MODEL, verbose_name='желающий')),
            ],
        ),
        migrations.RunPython(
            code=barter.migrations.0005_auto_20211002_1633.create_through_relations,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='item',
            name='wished_by',
        ),
        migrations.AddField(
            model_name='item',
            name='wished_by',
            field=models.ManyToManyField(blank=True, related_name='wished_items', through='barter.Wish', to=settings.AUTH_USER_MODEL, verbose_name='нужен'),
        ),
    ]
