# Generated by Django 3.2.7 on 2021-10-02 16:33
import datetime

from django.db import migrations


def create_through_relations(apps, schema_editor):
    Item = apps.get_model('barter', 'Item')
    Wish = apps.get_model('barter', 'Wish')
    for item in Item.objects.all():
        for wisher in item.wished_by.all():
            Wish(
                item=item,
                wisher=wisher,
                wished_at=datetime.datetime.now(),
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0004_wish'),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
