# Generated by Django 3.2.7 on 2021-10-02 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barter', '0004_wish_squashed_0007_item_wished_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish', to='barter.item', verbose_name='предмет'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='wisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish', to=settings.AUTH_USER_MODEL, verbose_name='желающий'),
        ),
    ]
