# Generated by Django 3.2.7 on 2021-10-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0005_auto_20211002_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='wished_by',
        ),
    ]
