# Generated by Django 3.2.7 on 2021-10-02 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barter', '0006_remove_item_wished_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='wished_by',
            field=models.ManyToManyField(blank=True, related_name='wished_items', through='barter.Wish', to=settings.AUTH_USER_MODEL, verbose_name='нужен'),
        ),
    ]
